### PR TITLE
Add hover events to some UI elements

### PR DESCRIPTION
**Pull request by mcfarlan**
One gripe I've had about the web version of Overcast is the lack of hover events. Something super tiny but really helps with basic user interaction.

Thanks for the great _port_ (for lack of words) of Marco's app. My daily podcast player while in-front of a computer.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you. I like this and intend to merge it, but I’m not yet completely sold on all the exact choices (like the black text on hover). I’ll take another look at it later.

**Comment by mcfarlan** [comment]
Thanks @vitorgalvao I'm happy to make any edits as needed, just holler

**Comment by vitorgalvao** [comment]
What I like:

* The hover inversion on delete and save.
* That the other links also change.

What I don’t like:

* The specific color of the text hovers. Black is too strong and the same color of the non-link text.
* The darker orange of the cell hovers. I liked the subtler original version better.

What I don’t think is necessary:

* The ease-out (does it really make a difference?).
* The transform. I only noticed the icons are scaling because I looked at the code, otherwise I wouldn’t have.

What isn’t working (but should, from the code):

* `Subscribe` should have the same effect of `Save`, bit it’s not working.
* `← All Podcasts` when on a page of an unsubscribed podcast does not change on hover.

**Comment by vitorgalvao** [comment]
I’ve fixed the bugs and made the other modifications. There’s not much left of your original code but you initiated the idea so I’ve preserved your commit and joined everything in https://github.com/vitorgalvao/fog/pull/9.

You may want to play around with it for and bit a give me your thoughts.

Thank you once more for the submission.

**Pull request closed without merging**
